version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: project-hub-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: project_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
